apiVersion: apps/v1
kind: Deployment
metadata:
    name: comcast-challenge
    labels:
        app: comcast-challenge
spec:
    replicas: 2
    selector:
        matchLabels:
            app: comcast-challenge
    template:
        metadata:
            labels:
                app: comcast-challenge
        spec:
            containers:
                - name: main
                  image: $IMAGE:$TAG
                  imagePullPolicy: Always
                  #          resources:
                  #            requests:
                  #              cpu: "10m"
                  #            limits:
                  #              cpu: "200m"
                  livenessProbe:
                      httpGet:
                          path: /ping
                          port: 3000
#                  envFrom:
#                      - secretRef:
#                            name: comcast-challenge
                  ports:
                      - containerPort: 3000
