apiVersion: v1
kind: Service
metadata:
    name: comcast-challenge
spec:
    ports:
        - port: 80
          targetPort: 3000
          protocol: TCP
    selector:
        app: comcast-challenge
---
#  this assumes ingress and dns is set up on the cluster correctly
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: comcast-challenge
    annotations:
        kubernetes.io/ingress.class: 'nginx'
        cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
    ingressClassName: 'nginx'
    tls:
        - hosts:
              - ccc.nboop.com
          secretName: ccc-nboop-com
    rules:
        - host: ccc.nboop.com
          http:
              paths:
                  - path: /
                    pathType: ImplementationSpecific
                    backend:
                        service:
                            name: comcast-challenge
                            port:
                                number: 80
